# SPDX-FileCopyrightText: 2022 - 2023 Peter Urban, Ghent University
#
# SPDX-License-Identifier: CC0-1.0

# Reusable workflow for setting up dependencies for GitHub Copilot CI
# Based on the Ubuntu 24.04 matrix job from ci-linux.yml

name: Setup Dependencies for Copilot

on:
  workflow_call:
    inputs:
      enable-ccache:
        description: 'Enable ccache for faster builds'
        required: false
        type: boolean
        default: true
      python-requirements:
        description: 'Install Python requirements from requirements.txt'
        required: false
        type: boolean
        default: true

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    
    steps:
    - name: Update package list
      run: |
        sudo apt update
    
    - name: Install system dependencies
      run: |
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
          sudo \
          git \
          git-lfs \
          build-essential \
          ccache \
          pkg-config \
          cmake \
          python3-pip \
          libboost-all-dev \
          libcurl4-openssl-dev \
          libeigen3-dev \
          libfmt-dev
    
    - name: Setup ccache
      if: ${{ inputs.enable-ccache }}
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: copilot-ci-ubuntu-22-04
    
    - name: Install Python build dependencies
      run: |
        pip install meson meson-python ninja pytest numpy
    
    - name: Install Python project requirements
      if: ${{ inputs.python-requirements }}
      run: |
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          echo "No requirements.txt found, skipping..."
        fi
