name: CI

on:
  push:
    branches: [ main ]
    #paths:
    #  - "**meson.build"
    #  - "**.cpp"
    #  - "**.c"
    #  - "**.h"
  pull_request:
    branches: [ main ]
    #paths:
    #  - "**meson.build"
    #  - "**.cpp"
    #  - "**.c"
    #  - "**.h"

# env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  #BUILD_TYPE: Release
  
jobs:

  build-on-linux:
    runs-on: ubuntu-latest
    container: ubuntu:latest #pull directly from dockerhub
    

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        
    - name: update apt and install prequisits
      run: apt update && apt-get install -y sudo python3-pip

    - name: install meson
      run: pip install meson ninja

    - name: install dependecies
      run: sudo apt-get install -y libboost-dev libcurl4-openssl-dev

    - name: configure meson
      run: meson setup builddir/
      env:
        CC: gcc

    - name: build and test
      run: meson test -C builddir/ -v
        
      
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Linux_Meson_Testlog
        path: builddir/meson-logs/testlog.txt

#   build-on-windows:
#     runs-on: windows-latest
#     steps:
#     - uses: actions/checkout@v1
#     - uses: actions/setup-python@v1
#       with:
#         python-version: '3.x'
#     - run: pip install meson ninja
#     - run: meson setup builddir/
#       env:
#         CC: gcc
#     - run: meson test -C builddir/ -v
#     - uses: actions/upload-artifact@v1
#       if: failure()
#       with:
#         name: Windows_Meson_Testlog
#         path: builddir/meson-logs/testlog.txt

#   macos:
#     runs-on: macos-latest
#     steps:
#     - uses: actions/checkout@v1
#     - uses: actions/setup-python@v1
#       with:
#         python-version: '3.x'
#     - run: brew install gcc
#     - run: pip install meson ninja
#     - run: meson setup builddir/
#       env:
#         CC: gcc
#     - run: meson test -C builddir/ -v
#     - uses: actions/upload-artifact@v1
#       if: failure()
#       with:
#         name: MacOS_Meson_Testlog
#         path: builddir/meson-logs/testlog.txt

      
